name: Keyball39 firmware

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip gcc-avr avr-libc dfu-programmer
          pip3 install qmk

      - name: Setup QMK
        run: |
          qmk setup -y
          ln -s $GITHUB_WORKSPACE/qmk_firmware/keyboards/keyball ~/qmk_firmware/keyboards/keyball

      - name: Compile firmware
        run: qmk compile -kb keyball/keyball39 -km default

      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: keyball39-firmware
          path: ~/qmk_firmware/.build/*.hex
