name: Keyball39 firmware (no external actions)

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        run: |
          git clone ${{ github.event.repository.clone_url }} .
          git fetch --all

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip gcc-avr avr-libc dfu-programmer
          pip3 install qmk

      - name: Setup QMK
        run: |
          qmk setup -y
          ln -s $GITHUB_WORKSPACE/qmk_firmware/keyboards/keyball ~/qmk_firmware/keyboards/keyball

      - name: Compile firmware
        run: |
          cd ~/qmk_firmware
          qmk compile -kb keyball/keyball39 -km default

      - name: Archive firmware
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp ~/qmk_firmware/.build/*.hex $GITHUB_WORKSPACE/artifacts/
